### ISSUE TITLE
农历算法有错误

### ISSUE THREAD

**Issue by deweizhu** [Lofanmi/chinese-calendar-golang#12]
例如：一九九六年八月二十五，干支历是：丁丑日，计算的结果显示【丙子】，这是错误的。
其实网上流传的各种库都是相互抄的，农历有很多错误的，1996年我都发现好几个了，建议用寿星天文历

**Comment by Lofanmi** [comment]
@deweizhu 新版master分支已经是寿星天文历算法，我核对了一下，返回的是【丁丑日】，是正确的。

请打开go.mod文件，将依赖更改为master版本，重新编译再试试。
