### ISSUE TITLE
缺少时辰的返回

### ISSUE THREAD

**Issue by gakkiismywife** [Lofanmi/chinese-calendar-golang#13]

**Comment by gakkiismywife** [comment]
农历获取int型日期的时候难道不是应该获取农历的日期吗 返回的依旧是公历的日期int 有点不合理吧

**Comment by Lofanmi** [comment]
@gakkiismywife 有例子吗？

**Comment by gakkiismywife** [comment]
`
func BuGua(ctx *gin.Context) {
	_ = ctx.Query("options")
	now := time.Now()
	c := GetLunar(now)

	month := c.Lunar.GetMonth()
	day := c.Lunar.GetDay()
	fmt.Println(now.Hour())
	hour := internal.GetTime(now.Hour())
	ctx.JSON(http.StatusOK, gin.H{
		"month": month,
		"day":   day,
		"hour":  hour,
	})
}

func GetLunar(now time.Time) *calendar.Calendar {

	return calendar.ByLunar(int64(now.Year()), int64(now.Month()), int64(now.Day()), int64(now.Hour()), int64(now.Minute()), int64(now.Second()), false)
}
`

我打印出来是这样的
`
{
day: 6,
hour: 0,
month: 9
}
`

**Comment by Lofanmi** [comment]
> ```
>  func BuGua(ctx *gin.Context) {
> 	  _ = ctx.Query("options")
> 	  now := time.Now()
> 	  c := GetLunar(now)
>   
> 	  month := c.Lunar.GetMonth()
> 	  day := c.Lunar.GetDay()
> 	  fmt.Println(now.Hour())
> 	  hour := internal.GetTime(now.Hour())
> 	  ctx.JSON(http.StatusOK, gin.H{
> 		  "month": month,
> 		  "day":   day,
> 		  "hour":  hour,
> 	  })
>   }
>   
>   func GetLunar(now time.Time) *calendar.Calendar {
>   
> 	  return calendar.ByLunar(int64(now.Year()), int64(now.Month()), int64(now.Day()), int64(now.Hour()), int64(now.Minute()), int64(now.Second()), false)
>   }
> ```
> 
> 我打印出来是这样的
> {
> day: 6,
> hour: 0,
> month: 9
> }

你的用法上有些问题，你应该传入阳历的时间，而不是用农历；另外时辰的接口只有在干支历，你可以参考我的代码：

```golang
package main

import (
	"fmt"

	"github.com/Lofanmi/chinese-calendar-golang/calendar"
)

func main() {
	// 日历传入当前的时间戳（阳历，2021-09-02 17时17分17秒 - 1631438237）
	c := calendar.ByTimestamp(1631438237)
	// c := calendar.ByTimestamp(time.Now().Unix()) 如果是现在可以这样传

	// Lunar 获取农历（旧历，二零二一年八月初六）
	fmt.Println(c.Lunar.GetMonth()) // 8
	fmt.Println(c.Lunar.GetDay())   // 6

	// 获取时辰，使用干支历
	fmt.Println(c.Ganzhi.HourZhi.Order())        // 10
	fmt.Println(c.Ganzhi.HourZhi.Alias() + "时") // 酉时，下午5点
}

```
