### ISSUE TITLE
支持的年份太少了

### ISSUE THREAD

**Issue by huoli4844** [Lofanmi/chinese-calendar-golang#14]
var solartermTimestamp = [...]int64{
	// 1904
	-2082349399, -2081077349, -2079801372, -2078519728, -2077229320, -2075929307,
	-2074617687, -2073295088, -2071960898, -2070617473, -2069265548, -2067908921,
	-2066549299, -2065191025, -2063836089, -2062488216, -2061148922, -2059820386,
	-2058503062, -2057197251, -2055902092, -2054616234, -2053337663, -2052063944,

请问一下这个时间如何扩展？

**Comment by Lofanmi** [comment]
@huoli4844 建议拉master分支, go.mod的版本改成master, 会自动识别, 新版本废弃时间戳的形式, 并和寿星万年历做了校对.

你说的1904年还不满足的话, 得手工扩展, 新版是儒略日, 需要补全各个年份的二十四节气
