### ISSUE TITLE
2033问题出来了 

### ISSUE THREAD

**Issue by Aquarian-Age** [Lofanmi/chinese-calendar-golang#4]
liangzi@xuan 5 04:42 >go run 一个阳历转农历的api接口.go 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4c5f5e]

goroutine 1 [running]:
github.com/Lofanmi/chinese-calendar-golang/ganzhi.(*Ganzhi).Animal(...)
        /home/xuan/go_work/pkg/mod/github.com/!lofanmi/chinese-calendar-golang@v0.0.0-20180418103304-7b76daa08da6/ganzhi/ganzhi.go:78
github.com/Lofanmi/chinese-calendar-golang/calendar.(*Calendar).ToJSON(0xc00000c120, 0xb, 0x15, 0xc, 0x1, 0x0)
        /home/xuan/go_work/pkg/mod/github.com/!lofanmi/chinese-calendar-golang@v0.0.0-20180418103304-7b76daa08da6/calendar/calendar.go:86 +0xffe
main.main()
        /home/xuan/nfs_share/golang/other/other/一个阳历转农历的api接口.go:18 +0xad
exit status 2

**Comment by Lofanmi** [comment]
@Aquarian-Age 感谢反馈，我看下。

**Comment by Aquarian-Age** [comment]
> @Aquarian-Age 感谢反馈，麻烦贴一下代码，我看下。

---------------------------
```golang
package main

import (
        "fmt"
        "github.com/Lofanmi/chinese-calendar-golang/calendar"
        "time"
)

func main() {
        t := time.Now()
        // 时间戳
        c := calendar.ByTimestamp(t.Unix())
        // 2. BySolar
        year, month, day, hour, minute, second := int64(2033), int64(11), int64(21), int64(12), int64(01), int64(00)
        // 公历
        c = calendar.BySolar(year, month, day, hour, minute, second)
        // 农历(最后一个参数表示是否闰月)
        bytes, err := c.ToJSON()
        if err != nil {
                fmt.Println(err)
        }
        fmt.Println(string(bytes))
}

```

**Comment by Lofanmi** [comment]
@Aquarian-Age 已经支持到3000年了。
